
export const Categories = {
    income: { name: "הכנסה", emoji: "💰", color: "#FFD700" },
    house: { name: "בית", emoji: "🏠", color: "#FF6347" },
    self: { name: "עצמי", emoji: "👤", color: "#9370DB" },
    subscriptions: { name: "מינויים", emoji: "📺", color: "#1E90FF" },
    restaurants: { name: "מסעדות/קפה", emoji: "🍴", color: "#FF8C00" },
    groceries: { name: "מצרכים", emoji: "🛒", color: "#FFDAB9" },
    workout: { name: "כושר", emoji: "🏋️‍♂️", color: "#FF69B4" },
    vacation: { name: "חופשה", emoji: "🌴", color: "#32CD32" },
    wedding: { name: "חתונה", emoji: "💍", color: "#DAA520" },
    animals: { name: "חיות", emoji: "🐶", color: "#8B4513" },
    transportation: { name: "תחבצ", emoji: "🚌", color: "#4682B4" },
    gifts: { name: "מתנות/תרומות", emoji: "🎁", color: "#FF1493" },
    savings: { name: "חסכונות", emoji: "💰", color: "#B8860B" },
    car: { name: "רכב", emoji: "🚗", color: "#2E8B57" },
    fees: { name: "עמלות", emoji: "💸", color: "#FF4500" },
    games: { name: "משחקים", emoji: "🎮", color: "#800080" },
    tech: { name: "טכנולוגיה", emoji: "💻", color: "#0000FF" },
    online: { name: "קנייה אונליין", emoji: "🛍️", color: "#0000FF" },
    entertainment: { name: "בידור", emoji: "🎬", color: "#FFD700" },
};

export const Budget = {
    '25': {
        '01': {
            income: 18000,
            self: 1000,
            restaurants: 1000,
            house: 1000,
            groceries: 1000,
            vacation: 1000,
            wedding: 1000,
            workout: 1000,
            subscriptions: 1000,
            animals: 1000,
            transportation: 1000,
            gifts: 1000,
            savings: 1000,
            car: 1000,
            fees: 1000,
            games: 1000,
            tech: 1000,
            online: 1000,
            entertainment: 1000,
        },
        '02': {
            income: 18669,
            self: 1100,
            restaurants: 1000,
            house: 800,
            groceries: 1000,
            vacation: 0,
            wedding: 0,
            workout: 300,
            subscriptions: 300,
            animals: 300,
            transportation: 100,
            gifts: 100,
            savings: 6000,
            car: 250,
            fees: 750,
            games: 0,
            tech: 0,
            online: 0,
            entertainment: 1000,
        },
        '03': {
            income: 15000,
            self: 1100,
            restaurants: 1000,
            house: 800,
            groceries: 1000,
            vacation: 0,
            wedding: 0,
            workout: 300,
            subscriptions: 300,
            animals: 300,
            transportation: 100,
            gifts: 100,
            savings: 6000,
            car: 250,
            fees: 750,
            games: 0,
            tech: 0,
            online: 0,
            entertainment: 1000,
        },
    },
}